Feat/#90
softeerbootcamp-3rd/Team9-HexaCore pull request #103
Opened 2024-02-14 14:15 UTC by jomulagy

close #90 
## DONE

- [x] DTO에 validater 추가하기
- [x] 예약 가능 일자 조회 관련 로직 수정 //Todo
- [x] 컨트롤러에 @Valid 어노테이션 추가

## 리뷰 포인트

- @NotNull 과 @Valid를 추가해서 controller에서 필수값 누락시 에러를 반환하게 수정
- method이름을 약속된 순서로 변경 carUpdate -> updateCar
- GetCarDateRangeResponse dto 생성
  - List dto와 dto 생성
  - List dto는 key를 제외한 value만으로 초기화
- GetCarResponseDto 에서 dateRanges 수정
  - key를 제외한 value만으로 초기화

2024-02-14 15:09 UTC, Yoon-Suji commented on server/src/main/java/com/hexacore/tayo/car/dto/GetCarDateRangeResponseDto.java
> +}
Inner class로 관리하니까 깔끔하고 좋네요👍

2024-02-14 15:14 UTC, Yoon-Suji commented on server/src/main/java/com/hexacore/tayo/car/model/CarType.java
>      }
필드명을 type -> value로 바꿨으니 getType도 getValue로 바꾸는 게 좋지 않을까요?

2024-02-15 00:28 UTC, timido7021 requested changes
valid 추가해서 필수값을 지정한 부분이 좋습니다. 수고하셨어요!

2024-02-15 00:28 UTC, timido7021 commented on server/src/main/java/com/hexacore/tayo/car/dto/GetCarDateRangeResponseDto.java
> +        private final List<String> carDateRange = new ArrayList<>();
추후에 `List<String>` 타입을 `CarDateRangeDto`로 #101 이슈 진행하면서 변경하겠습니다!

2024-02-15 00:31 UTC, timido7021 approved these changes
Approve한다는게 실수로 Request Change를 했습니다.

2024-02-15 01:23 UTC, jomulagy commented on server/src/main/java/com/hexacore/tayo/car/model/CarType.java
>      }
수정하겠습니다

2024-02-15 01:27 UTC, Yoon-Suji approved these changes

2024-02-15 01:28 UTC, merged