Bug/#122
softeerbootcamp-3rd/Team9-HexaCore pull request #124
Opened 2024-02-15 17:35 UTC by jomulagy

close #122 
## DONE

[x] 예약 가능 날짜 버그 수정

## 리뷰 포인트

- 예약이 된 날짜 제외하고 반환

2024-02-15 17:55 UTC, SuHyeon00 commented on server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
> +                    .toList();
carDateRange와 연결된 모든 예약 정보를 갖고오게 된다면 예약 상태가 Cancel인 경우의 예약 정보도 갖고오게 되는 것 아닐까요..?

2024-02-15 17:56 UTC, jomulagy commented on server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
> +                    .toList();
수정하겠습니다

2024-02-15 18:00 UTC, SuHyeon00 requested changes
현재 dev 브랜치 기준으로 기존 `SubCategory`를 `Subcategory`로 변경한 것으로 알고 있습니다. dev pull 한 번 받고 다시 push 해주실 수 있을까요?

2024-02-15 21:06 UTC, SuHyeon00 approved these changes
수고하셨습니다!

2024-02-16 03:33 UTC, timido7021 approved these changes
수고하셨습니다!

2024-02-16 04:29 UTC, thecloer commented on server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
> +    }
`carDateRange[0]` 과 해당 range에 포함된 예약의 `reservation[0]`이 같을 경우 start > end인 범위가 결과에 포함될 것 같아요! 이 부분 한번 확인해 주시겠어요??

2024-02-16 17:38 UTC, jomulagy commented on server/src/main/java/com/hexacore/tayo/car/CarSpecifications.java
맞습니다

2024-02-16 17:39 UTC, jomulagy commented on server/src/main/java/com/hexacore/tayo/car/dto/GetCarResponseDto.java
> +    }
조건문으로 비교 하고 있습니다. 예외케이스 수정했습니다

2024-02-16 17:39 UTC, merged